sudo: required

services:
  - docker

language: node_js

git:
    submodules: false

env:
  global:
    - GH_REF: github.com/sicilia-io/style-guide
    - secure: "kyGTUP/BO+USoRBVPvCc9TrbEWBYTe/6f8bsRx5op9yy56U1KIaUnudtn16GBIlX3wpaCECL8gkIQZ2x7cnS5rXlhlUDWMz94DglySM8t05o1ItiYDXf4MU2GPbrBz9JJbU7BsN3Z3xaQVtdZ+kVpnkf8gz5KySOXgwV7MjoVJB6KcdgpaFgmPT9M2ROCRmiqzynxBWwfGTaehCDlCrMMLXmQuRLiM3AHDHMlxRHW2aT9dNAVl1LEFFCkfpNK3FZHNCInD06wSI8GePaD1hl9zejOYx6FuKa9g67XH7+YmDLuTJfErb1H6/GrRoGJ9/IlS/WOjdcxy/1iX6312MY79qTgjO52G8G+Tcz1SGlIq4nRJpZMZz20nvCKyJh7R8ZO7qB12RVq6CsVxKrA7t/eXTs/Tz5phUtoehAZ/gi7Q0l+mv44iKkWEFJIHx8hAESffQrIuS0Hu/XKTsLiGbGSOfeK+iA2qYJ/KGJcCMqe7MquI0aCpPiY+T9ZtOa/qxV+VWfyY/1jIuFr09CpbvVdLG0PDHZKRKn5I4bmHbhpaP+J5lKWZyv2/jRebGq5Z9VF/U4y/U2yR+PUG7JHwj2c8f1TNpXuClmo064VjiLJsTGQoCAYiipdTrLHkQNff319Pw5jyfaBe+UilOrmPFvqsHBlSOxbN1ftMZAAZEYQK0="

script: make build

after_success:
  - make publish-gh-pages
